Build not only x64
Icinga/docker-icingaweb2 pull request #104
Opened 2023-01-17 12:47 UTC by Al2Klimov

Basically a C&P from Icinga/docker-icingadb#56

2023-01-17 14:15 UTC, Al2Klimov commented
## TODO

* #105
* Icinga/docker-icingadb#56

2023-01-18 12:16 UTC, Al2Klimov commented
Test pipeline:

https://github.com/Icinga/icingaweb2/actions/runs/3939384017/jobs/6759118416

2023-09-07 13:24 UTC, Al2Klimov commented
v2.12 makes big progress (https://github.com/orgs/Icinga/projects/16) and shouldn't miss this one.

2023-09-07 13:27 UTC, Al2Klimov commented
Test pipeline: https://github.com/Icinga/icingaweb2/actions/runs/6110383935/job/16583269993

2023-09-07 13:48 UTC, Al2Klimov commented
OK, tbh IW2 doesn't push on branches. But on dispatches: https://github.com/Icinga/icingaweb2/actions/runs/6110601542/job/16583983067

2023-09-07 14:06 UTC, Al2Klimov commented
That worked btw.: https://hub.docker.com/layers/icinga/icingaweb2/Al2Klimov-test-ARM/images/sha256-24a50dc9c0332220d71df2ffc7ae9a5dd2da3ae3d92a78ae3b2887826cdd49aa?context=explore

2023-09-08 10:28 UTC, Al2Klimov commented
> v2.12 makes big progress (https://github.com/orgs/Icinga/projects/16) and shouldn't miss this one.

Not to mention that more and more of the IW2 people get M2 machines, e.g. @theFeu.

2023-09-14 11:14 UTC, julianbrost requested changes

2023-09-14 11:14 UTC, julianbrost commented on build.bash
> +TAG="${4:-test}"
That's a strange order of arguments where `$2` has a default but `$3` hasn't. The optional ones should come at the end.

2023-09-26 09:45 UTC, Al2Klimov commented on build.bash
> +TAG="${4:-test}"
But $3 IS optional. See the case/esac below.

2023-09-26 13:16 UTC, julianbrost commented on build.bash
> +TAG="${4:-test}"
It doesn't look like it is though. So explicitly providing a default value would be nice.

Currently, that list of variable assignments is the only thing that somewhat tells you how to call that script, and it's totally unclear that `ACTION=''` is the intended default.

Anyways, updating the already outdated usage output would be a good idea.

2023-10-05 10:22 UTC, Al2Klimov commented on build.bash
> +TAG="${4:-test}"
Done.

2023-10-06 09:30 UTC, julianbrost commented
The PR for this repo should be fine now. This obsoletes a section from [`RELEASE.md` in icingaweb2](https://github.com/Icinga/icingaweb2/blob/e5f6fc276a29bd716c2799b9a11b0d63b85d0ef2/RELEASE.md#docker). Is there already a PR that updates that?

2023-10-06 09:31 UTC, Al2Klimov commented
Not yet. One step after the other.

2023-10-25 10:58 UTC, Al2Klimov commented
Now there is a PR.

2023-10-25 11:18 UTC, julianbrost approved these changes
Fine for me, but please coordinate merging with @nilmerg as this affects the Icinga Web release workflow.

2023-10-25 11:32 UTC, merged