Install standard ca-certificates
Icinga/docker-icingaweb2 pull request #54
Opened 2021-08-30 16:05 UTC by nneul

Without standard certificates, NO attempted SSL connection will work unless you pass in your own ca-certs - even to endpoints providing a fully well-known-CA trusted cert.

2021-08-30 16:08 UTC, nneul commented
Signed.

2021-08-31 06:43 UTC, bobapple commented
@cla-bot check

2021-08-31 08:37 UTC, Al2Klimov requested changes
Everything is fine except one little thing:

Please keep the list sorted alphabetically.

(No need to squash commits.)

2021-08-31 12:06 UTC, Al2Klimov approved these changes

2021-08-31 12:10 UTC, merged