Entrypoint: re-try database connection on error for <=5m
Icinga/docker-icingaweb2 pull request #89
Opened 2022-07-18 13:40 UTC by Al2Klimov

2022-07-18 13:41 UTC, Al2Klimov commented
```
...
[Mon Jul 18 13:29:44.000000 2022] [docker_entrypoint:error] [pid 11] DOCKERE: Can't connect to database: SQLSTATE[HY000] [2002] Connection refused
[Mon Jul 18 13:29:45.000000 2022] [docker_entrypoint:error] [pid 11] DOCKERE: Can't connect to database: SQLSTATE[HY000] [2002] Connection refused
[Mon Jul 18 13:29:46.000000 2022] [docker_entrypoint:error] [pid 11] DOCKERE: Can't connect to database: SQLSTATE[HY000] [2002] Connection refused
ERROR: PDOException in /usr/share/icingaweb2/modules/setup/library/Setup/Utils/DbTool.php:352 with message: SQLSTATE[HY000] [2002] Connection refused
[Mon Jul 18 13:29:47.215484969 2022] [docker_entrypoint:crit] [pid 1] DOCKERE: exit status 1
```

```
ERROR: PDOException in /usr/share/icingaweb2/modules/setup/library/Setup/Utils/DbTool.php:352 with message: SQLSTATE[HY000] [1045] Access denied for user 'icingaweb'@'172.17.0.3' (using password: YES)
[Mon Jul 18 13:31:48.051163193 2022] [docker_entrypoint:crit] [pid 1] DOCKERE: exit status 1
```

2022-12-08 14:08 UTC, Al2Klimov commented
Please consider this for (i.e. before) the upcoming release.

2023-01-18 09:01 UTC, Al2Klimov commented
_PING_

2023-01-20 14:29 UTC, lippserd requested changes

2023-01-20 14:29 UTC, lippserd commented on entrypoint/db-init/application/clicommands/DbCommand.php
> +                sleep(1);
I would only sleep every 3 seconds. Otherwise this pollutes the log too much.

2023-01-20 14:29 UTC, lippserd commented on entrypoint/db-init/application/clicommands/DbCommand.php
> +                sleep(1);
Or even longer.

2023-01-20 15:10 UTC, lippserd approved these changes

2023-01-20 15:12 UTC, Al2Klimov commented
Feel free to merge it if OK.

2023-01-20 15:27 UTC, merged